/**
 * Terms of Service page — structured SaaS Terms template.
 *
 * Uses [Company Name] and [Date] placeholders for final legal review.
 * Pass `approved={true}` to LegalShell once counsel signs off.
 */
import type { Metadata } from "next";
import { LegalShell } from "@/components/public/LegalShell";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Bright.Experience terms of service and conditions of use.",
  openGraph: {
    title: "Terms of Service — Bright.Experience",
    description: "Terms of service and conditions of use.",
  },
};

const LAST_UPDATED = "2026-05-01";

export default function TermsPage() {
  return (
    <LegalShell
      eyebrow="Legal"
      title="Terms of Service"
      lastUpdatedIso={LAST_UPDATED}
      approved
    >
      <Block heading="1. Definitions">
        <p>
          &ldquo;[Company Name]&rdquo; refers to Bright.Blue Events Ltd, the
          provider of the Bright.Experience platform. &ldquo;Service&rdquo;
          means the SaaS platform, event machines, and associated deliverables.
          &ldquo;Customer&rdquo; means any individual or entity that registers
          for an account or books an activation. &ldquo;Content&rdquo; means
          any materials uploaded to or generated by the Service.
        </p>
      </Block>
      <Block heading="2. Account Terms">
        <p>
          You must provide accurate and complete information when creating an
          account. You are responsible for maintaining the security of your
          credentials and for all activity under your account. You must be at
          least 18 years old to use the Service. [Company Name] reserves the
          right to suspend accounts that violate these terms.
        </p>
      </Block>
      <Block heading="3. Payment">
        <p>
          Pricing is set forth in the applicable quote or package selection.
          Invoices are due within 14 days unless otherwise agreed. A deposit
          is required to confirm a booking; the balance is invoiced upon event
          completion. Late payments accrue interest at 4% above the Bank of
          England base rate. All prices are exclusive of VAT unless stated
          otherwise.
        </p>
      </Block>
      <Block heading="4. Acceptable Use">
        <p>
          You may not use the Service for unlawful purposes, to transmit
          harmful code, to infringe third-party rights, or to interfere with
          the platform&apos;s operation. Content uploaded must comply with all
          applicable advertising standards. [Company Name] may remove Content
          or suspend access for violations without prior notice.
        </p>
      </Block>
      <Block heading="5. Intellectual Property">
        <p>
          The Service, its design, code, and brand assets remain the exclusive
          property of [Company Name]. Customer retains ownership of all
          Content they upload. Leads and engagement data captured during your
          activation are exclusively yours. [Company Name] may use anonymised,
          aggregate metrics for benchmarking and product improvement.
        </p>
      </Block>
      <Block heading="6. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, [Company Name]&apos;s total
          liability arising from or related to the Service is limited to the
          fees paid by the Customer in the 12 months preceding the claim. In
          no event shall [Company Name] be liable for indirect, incidental,
          special, consequential, or punitive damages, including loss of
          profits, revenue, or data.
        </p>
      </Block>
      <Block heading="7. Termination">
        <p>
          Either party may terminate with 30 days&apos; written notice.
          [Company Name] may terminate immediately for breach of these terms.
          Upon termination, Customer data will be available for export for 30
          days, after which it may be deleted. Cancellation fees apply per the
          booking confirmation: more than 30 days&apos; notice forfeits the
          deposit; less than 7 days&apos; notice incurs the full booking value.
        </p>
      </Block>
      <Block heading="8. Governing Law">
        <p>
          These terms are governed by the laws of England and Wales. Any
          disputes shall be subject to the exclusive jurisdiction of the
          courts of England and Wales. If any provision is found unenforceable,
          the remaining provisions continue in full force.
        </p>
      </Block>
      <Block heading="9. Contact">
        <p>
          Questions about these terms? Email{" "}
          <a
            className="text-primary underline underline-offset-4"
            href="mailto:hello@brightblue.co.uk"
          >
            hello@brightblue.co.uk
          </a>
          .
        </p>
        <p className="mt-2 text-xs text-muted-foreground">
          Last reviewed: [Date] — [Company Name], registered in England &amp;
          Wales.
        </p>
      </Block>
    </LegalShell>
  );
}

function Block({
  heading,
  children,
}: {
  heading: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold text-foreground">{heading}</h2>
      <div className="mt-2 text-sm leading-relaxed text-muted-foreground">
        {children}
      </div>
    </section>
  );
}
