import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Reference project (kept for design parity, not part of the app):
    "TheoCloudRedesign-main/**",
    // Vendored / minified assets:
    "public/**/*.min.mjs",
    "public/**/*.min.js",
    // Generated by `npm run test:coverage`:
    "coverage/**",
  ]),
  {
    rules: {
      // A leading underscore is how this codebase says "required by the
      // signature, deliberately unused" — mock implementations and test
      // doubles rely on it constantly.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
]);

export default eslintConfig;
