/**
 * The interactive sample proof-of-performance report: the artefact a
 * sponsor receives within 24 hours of show close, rendered with clearly
 * labelled illustrative data so reps can show the output before anything
 * ships. Headlines derive from the day rows via `reportTotals`, so the
 * page can never disagree with its own charts.
 */
"use client";

import { Download } from "lucide-react";

import { CloudAreaChart, CloudBarChart } from "@/components/cloud/ChartCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatCount, formatUsdWhole, INDUSTRY_CPL } from "@/lib/informa/kit-math";
import {
  benchmarkSavingsPct,
  hourlyAveragePlays,
  optInRatePct,
  playCeilingPerHour,
  reportCpl,
  reportTotals,
  SAMPLE_REPORT,
} from "@/lib/informa/sample-report";

/** Static asset pre-generated by scripts/informa-report-pdf (Playwright). */
export const SAMPLE_REPORT_PDF = "/downloads/Bright.Blue-Informa-Sample-Report.pdf";

function Stat({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return (
    <div className="rounded-2xl border border-border/70 bg-card/50 p-5">
      <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
        {label}
      </p>
      <p className="mt-1 text-3xl font-semibold tabular-nums">{value}</p>
      {hint ? <p className="mt-1 text-xs text-muted-foreground">{hint}</p> : null}
    </div>
  );
}

function Panel({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-2xl border border-border/70 bg-card/50 p-6">
      <h3 className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">
        {title}
      </h3>
      <div className="mt-4">{children}</div>
    </div>
  );
}

export function SampleReportView() {
  const totals = reportTotals(SAMPLE_REPORT.byDay);
  const cpl = reportCpl(SAMPLE_REPORT.meta.priceUsd, totals.leads);
  const optIn = optInRatePct(totals.plays, totals.leads);
  const hourlyAvg = hourlyAveragePlays(
    SAMPLE_REPORT.byHour,
    SAMPLE_REPORT.byDay.length,
  );
  const hourlyCeiling = playCeilingPerHour(SAMPLE_REPORT.avgSessionSeconds);

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex flex-wrap items-center gap-3">
          <Badge variant="outline" className="border-brand-cyan/60 text-brand-cyan">
            {SAMPLE_REPORT.meta.label}
          </Badge>
          <span className="text-sm text-muted-foreground">
            {SAMPLE_REPORT.meta.product} · {SAMPLE_REPORT.meta.show}
          </span>
        </div>
        <Button asChild variant="outline" className="gap-2">
          <a href={SAMPLE_REPORT_PDF} download>
            <Download className="size-4" aria-hidden />
            Download as PDF
          </a>
        </Button>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <Stat
          label="Completed plays"
          value={formatCount(totals.plays)}
          hint={`${SAMPLE_REPORT.avgSessionSeconds} seconds of hands-on brand time each, on average`}
        />
        <Stat
          label="Opted-in leads"
          value={formatCount(totals.leads)}
          hint={`${optIn}% of plays opted in at the machine`}
        />
        <Stat
          label="Cost per opted-in lead"
          value={cpl == null ? "n/a" : formatUsdWhole(cpl)}
          hint={
            cpl == null
              ? undefined
              : `${benchmarkSavingsPct(cpl)}% under the ${formatUsdWhole(INDUSTRY_CPL.low)} industry low`
          }
        />
        <Stat
          label="Ad-loop content plays"
          value={formatCount(SAMPLE_REPORT.adLoop.contentPlays)}
          hint="Logged on the machine, not modelled"
        />
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel title="Engagement by hour">
          <div className="h-64">
            <CloudAreaChart
              data={hourlyAvg}
              xKey="hour"
              yKey="plays"
              name="Avg plays per show hour"
            />
          </div>
          <p className="mt-3 text-xs text-muted-foreground">
            Average per show day, show-floor local time. A{" "}
            {SAMPLE_REPORT.avgSessionSeconds}-second guided session caps one
            machine near {hourlyCeiling} plays an hour, so the late-morning
            peak is running close to capacity — the shape argues for the
            placement, the ceiling argues for a second machine.
          </p>
        </Panel>
        <Panel title="Day by day">
          <div className="h-64">
            <CloudBarChart
              data={[...SAMPLE_REPORT.byDay]}
              xKey="label"
              series={[
                { key: "plays", name: "Completed plays", tone: "primary" },
                { key: "leads", name: "Opted-in leads", tone: "accent" },
              ]}
              showLegend
            />
          </div>
          <p className="mt-3 text-xs text-muted-foreground">
            Leads track plays because opt-in happens at the machine, before
            play, not in a follow-up email.
          </p>
        </Panel>
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <Panel title="What arrived with each lead">
          <ul className="space-y-4">
            {SAMPLE_REPORT.leadQuality.map((row) => (
              <li key={row.label}>
                <div className="flex items-baseline justify-between gap-3">
                  <span className="text-sm font-medium">{row.label}</span>
                  <span className="text-lg font-semibold tabular-nums">
                    {formatCount(row.count)}
                  </span>
                </div>
                <p className="mt-0.5 text-xs text-muted-foreground">{row.detail}</p>
              </li>
            ))}
          </ul>
        </Panel>
        <Panel title="The screen loop">
          <p className="text-3xl font-semibold tabular-nums">
            {formatCount(SAMPLE_REPORT.adLoop.contentPlays)}
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            content plays across {SAMPLE_REPORT.adLoop.slots} slots and up to{" "}
            {SAMPLE_REPORT.adLoop.screens} screens
          </p>
          <p className="mt-3 text-xs leading-relaxed text-muted-foreground">
            {SAMPLE_REPORT.adLoop.note}
          </p>
        </Panel>
        <Panel title="Fulfilment, reconciled">
          <p className="text-3xl font-semibold tabular-nums">
            {formatCount(SAMPLE_REPORT.fulfilment.samplesDispensed)}
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            samples dispensed · {SAMPLE_REPORT.fulfilment.stockOuts} stock-outs
          </p>
          <p className="mt-3 text-xs leading-relaxed text-muted-foreground">
            {SAMPLE_REPORT.fulfilment.note}
          </p>
        </Panel>
      </div>

      <p className="text-xs leading-relaxed text-muted-foreground/70">
        {SAMPLE_REPORT.meta.disclaimer} Benchmark: {formatUsdWhole(INDUSTRY_CPL.low)} to{" "}
        {formatUsdWhole(INDUSTRY_CPL.high)} per trade show lead (Exhibit Surveys 2025,
        ShowHero State of Trade Shows 2026, CEIR blended average).
      </p>
    </div>
  );
}
