/**
 * GET /api/partner-resources/:key
 *
 * Serves real, generated partner sales collateral so the reseller portal's
 * Resources library has working downloads instead of "Coming Soon" buttons.
 * Data-style resources are emitted as branded XLSX; document-style resources
 * as Markdown one-pagers. Auth required (any signed-in user).
 */
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { excelResponse } from "@/lib/exports/excel";

export const dynamic = "force-dynamic";

type SheetDef = {
  name: string;
  columns: { header: string; key: string; width?: number }[];
  rows: Record<string, unknown>[];
};

const XLSX_RESOURCES: Record<string, { title: string; filename: string; sheets: SheetDef[] }> = {
  "vending-product-sheet": {
    title: "Bright.Vend Pro — Product Sheet",
    filename: "bright-vend-pro-spec.xlsx",
    sheets: [
      {
        name: "Specification",
        columns: [
          { header: "Attribute", key: "attribute", width: 28 },
          { header: "Detail", key: "detail", width: 52 },
        ],
        rows: [
          { attribute: "Machine", detail: "Bright.Vend Pro interactive vending unit" },
          { attribute: "Footprint", detail: "0.9m × 0.9m × 2.1m (W×D×H)" },
          { attribute: "Screen", detail: "55\" portrait 4K touch display" },
          { attribute: "Dispense", detail: "Up to 6 SKUs, 240 units capacity" },
          { attribute: "Game library", detail: "12 pre-built games, fully brandable" },
          { attribute: "Data capture", detail: "Email, phone, custom fields, consent" },
          { attribute: "Telemetry", detail: "Live plays, leads, dwell, prize redemption" },
          { attribute: "Power", detail: "Standard 13A socket, 300W draw" },
          { attribute: "Connectivity", detail: "4G + Wi-Fi failover" },
        ],
      },
    ],
  },
  "activation-product-sheet": {
    title: "Bright.Activate — Product Sheet",
    filename: "bright-activate-spec.xlsx",
    sheets: [
      {
        name: "Specification",
        columns: [
          { header: "Attribute", key: "attribute", width: 28 },
          { header: "Detail", key: "detail", width: 52 },
        ],
        rows: [
          { attribute: "Machine", detail: "Bright.Activate experiential unit" },
          { attribute: "Footprint", detail: "Modular — 1m to 4m wide configurations" },
          { attribute: "Screen", detail: "Up to 86\" landscape touch + side panels" },
          { attribute: "Game library", detail: "20+ games incl. AR, spin-to-win, quiz" },
          { attribute: "Customisation", detail: "Full wrap, custom game skins, prize logic" },
          { attribute: "Data capture", detail: "Email, phone, custom fields, consent" },
          { attribute: "Telemetry", detail: "Live plays, leads, dwell, heat by hour" },
          { attribute: "Staffing", detail: "Self-serve or brand-ambassador assisted" },
          { attribute: "Connectivity", detail: "4G + Wi-Fi failover" },
        ],
      },
    ],
  },
};

function markdownResource(key: string): { filename: string; body: string } | null {
  switch (key) {
    case "pitch-deck":
      return {
        filename: "bright-partner-pitch-deck.md",
        body: `# Bright.Blue — Partner Pitch Deck

## 1. The opportunity
Brands want measurable, premium in-person activations. Bright.Blue turns any
venue or event into an interactive, data-capturing experience.

## 2. What we do
Interactive vending + activation machines that run brandable games, capture
leads, and stream live telemetry to a premium client portal.

## 3. Why partners win
- Recurring commission on every booking you refer or send.
- Co-branded portal — your logo, your colours, your clients.
- We handle delivery, creative, logistics, QA and reporting end to end.

## 4. Proof
- Coca-Cola: 21,000 interactions across a 12-city summer tour.
- Diageo: 2,400 prize redemptions across three Six Nations match days.

## 5. How to sell it
1. Share your partner referral link, or send a quote from your portal.
2. We qualify, scope and deliver.
3. You earn commission and see every quote in your pipeline.

_Generated by Bright.Experience for partner use._`,
      };
    case "brand-guidelines":
      return {
        filename: "bright-brand-guidelines.md",
        body: `# Bright.Blue — Co-Branding Guidelines

## Logo usage
- Always pair your logo with "in partnership with Bright.Blue".
- Maintain clear space equal to the height of the "B" around the lockup.
- Never recolour, stretch, or add effects to the Bright.Blue mark.

## Colour
- Cobalt: #3366FF (primary)
- Deep Ink: #0E1428 (text / backgrounds)
- Cyan accent: #80E8FF

## Typography
- Headings: editorial serif/display
- Body: clean grotesque sans

## Tone
Premium, confident, plain-spoken. Sell the outcome (engagement, leads,
proof), not the hardware.

_Generated by Bright.Experience for partner use._`,
      };
    case "case-study-cocacola":
      return {
        filename: "case-study-coca-cola.md",
        body: `# Case Study — Coca-Cola Summer Campaign

## Challenge
Drive memorable, measurable engagement across a multi-city summer tour.

## Solution
Bright.Vend Pro units with a branded "Spin & Reveal" game dispensing chilled
samples, capturing opt-in leads at every play.

## Results
- 21,000+ interactions across the 12-city tour
- 480k+ on-site impressions
- Lead capture 16% above forecast
- Interactions beat the forecast by 15%

> "The portal made proving ROI to our stakeholders effortless." — Brand Lead

_Generated by Bright.Experience for partner use._`,
      };
    case "case-study-diageo":
      return {
        filename: "case-study-diageo.md",
        body: `# Case Study — Diageo Matchday Fan Zone

## Challenge
Turn high-energy matchday crowds into memorable, measurable brand moments.

## Solution
Bright.Vend Pro units running a branded prize game with instant-win logic and
consented data capture across three Six Nations match days.

## Results
- 3,000 samples over three match days
- 2,400 instant-win prize redemptions
- 33% play-to-lead conversion

_Generated by Bright.Experience for partner use._`,
      };
    case "demo-reel":
      return {
        filename: "bright-demo-reel-brief.md",
        body: `# Bright.Blue — Product Demo Reel (Brief)

A 90-second sizzle reel showing machines and games in action at live events.

## How to use it
- Open or warm up a client meeting.
- Pair with the pitch deck section 4 (Proof).

## Request the file
High-res video files are distributed per-campaign to keep them current.
Request the latest cut from your Bright.Blue account manager, or embed the
portal's live event dashboards for real, up-to-date proof.

_Generated by Bright.Experience for partner use._`,
      };
    default:
      return null;
  }
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ key: string }> },
) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { key } = await params;

  const xlsx = XLSX_RESOURCES[key];
  if (xlsx) {
    return excelResponse(xlsx.sheets, xlsx.title, xlsx.filename);
  }

  const md = markdownResource(key);
  if (md) {
    return new Response(md.body, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="${md.filename}"`,
      },
    });
  }

  return NextResponse.json({ error: "Resource not found" }, { status: 404 });
}
