/** Internal-actionable archetypes: intake, bookings, reviews, studio, tasks. */

import { TWENTY_FOUR, FORTY_EIGHT } from "./cadence";
import type { ArchetypeSection } from "./types";

export const internalArchetypes = {
  "proposal.intake_received": {
    kind: "proposal.intake_received",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required",
    subjectTemplate: "New proposal intake — {contactName}",
    bodyTemplate:
      "{contactName} just submitted a proposal intake. Capabilities are pre-tagged on the quote — first response within four hours.",
    linkTemplate: "/admin/quotes/{quoteId}",
    ownerResolver: "event_account_executive",
    reminderCadence: {
      firstAfterHours: 4,
      intervalHours: 4,
      maxEscalations: 3,
    },
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
  },
  "proposal.walkthrough_booked": {
    kind: "proposal.walkthrough_booked",
    classOf: "fyi",
    priority: "high",
    eyebrow: "FYI",
    subjectTemplate: "Walkthrough booked — {slotLabel}",
    bodyTemplate:
      "The customer booked their 15-minute proposal walkthrough for {slotLabel}. Prep the tailored proposal before the call.",
    linkTemplate: "/admin/quotes/{quoteId}",
    ownerResolver: "event_account_executive",
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
  },
  "booking.received": {
    kind: "booking.received",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required",
    subjectTemplate: "New booking — {contactName}",
    bodyTemplate:
      "{contactName} just booked through the configurator. Confirm payment intent, kick off the event, and acknowledge within four hours.",
    linkTemplate: "/admin/quotes/{quoteId}",
    ownerResolver: "event_account_executive",
    reminderCadence: {
      firstAfterHours: 4,
      intervalHours: 4,
      maxEscalations: 3,
    },
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
  },
  "quote.accepted": {
    kind: "quote.accepted",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required",
    subjectTemplate: "Proposal accepted — kick off {eventName}",
    bodyTemplate:
      "The customer accepted the proposal. Time to spin up the event and send the brief.",
    linkTemplate: "/admin/quotes/{quoteId}",
    ownerResolver: "event_members_internal",
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
  },
  "asset.review_needed": {
    kind: "asset.review_needed",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required",
    subjectTemplate: "{assetName} needs a creative review",
    bodyTemplate:
      "{contactName} uploaded {assetName} for {eventName}. Review against the spec — approve it or send back with a note.",
    linkTemplate: "/admin/asset-reviews",
    ownerResolver: "event_creative_lead",
    reminderCadence: {
      firstAfterHours: TWENTY_FOUR,
      intervalHours: TWENTY_FOUR,
      maxEscalations: 3,
    },
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
    roleScope: ["creative_lead", "events_lead", "admin", "developer"],
  },
  "briefing.submitted": {
    kind: "briefing.submitted",
    classOf: "fyi",
    priority: "normal",
    eyebrow: "FYI",
    subjectTemplate: "{contactName} submitted the brief for {eventName}",
    bodyTemplate:
      "The brief is in. The next step is yours — read it through and queue up the production milestones.",
    linkTemplate: "/events/{eventId}/briefing",
    ownerResolver: "event_creative_lead",
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
  },
  "studio.request_submitted": {
    kind: "studio.request_submitted",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required",
    subjectTemplate: "New Studio order — {title}",
    bodyTemplate:
      "A new Bright.Studio order needs a producer. Service: {serviceType}. Open the portal to take it.",
    linkTemplate: "/studio",
    ownerResolver: "event_creative_lead",
    reminderCadence: {
      firstAfterHours: TWENTY_FOUR,
      intervalHours: TWENTY_FOUR,
      maxEscalations: 3,
    },
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "internal",
    roleScope: ["creative_lead", "events_lead", "admin", "developer"],
  },
  "studio.status_changed": {
    kind: "studio.status_changed",
    classOf: "fyi",
    priority: "normal",
    eyebrow: "FYI",
    subjectTemplate: "Studio update on {title}",
    bodyTemplate: "Status changed to {status}. Open the portal for the latest.",
    linkTemplate: "/events/{eventId}/studio",
    ownerResolver: "event_members_internal",
    defaults: { inPortal: true, emailMode: "digest" },
    audience: "internal",
  },
  "task.assigned": {
    kind: "task.assigned",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required",
    subjectTemplate: "{taskTitle} is on your plate",
    bodyTemplate: "Due {dueDate}. Open the task to start it or hand it off.",
    linkTemplate: "/events/{eventId}/actions",
    ownerResolver: "task_assignee",
    reminderCadence: {
      firstAfterHours: TWENTY_FOUR,
      intervalHours: TWENTY_FOUR,
      maxEscalations: 3,
    },
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "both",
  },
  "task.completed": {
    kind: "task.completed",
    classOf: "fyi",
    priority: "normal",
    eyebrow: "Progress update",
    subjectTemplate: "{taskTitle} completed",
    bodyTemplate:
      "A blocking action on {eventName} has been marked as complete. The event may now be eligible to advance to the next stage.",
    linkTemplate: "/events/{eventId}/actions",
    ownerResolver: "event_account_executive",
    defaults: { inPortal: true, emailMode: "digest" },
    audience: "internal",
  },
  "task.overdue": {
    kind: "task.overdue",
    classOf: "action_required",
    priority: "high",
    eyebrow: "Action required — overdue",
    subjectTemplate: "{taskTitle} is overdue",
    bodyTemplate:
      "This task was due {dueDate}. Open it to update the status — even a quick note keeps the timeline honest.",
    linkTemplate: "/events/{eventId}/actions",
    ownerResolver: "task_assignee",
    reminderCadence: {
      firstAfterHours: 0,
      intervalHours: FORTY_EIGHT,
      maxEscalations: 3,
      ccAccountManagerAtLevel: 2,
    },
    defaults: { inPortal: true, emailMode: "immediate" },
    audience: "both",
  },
} satisfies ArchetypeSection;
